version: "3"
services:
  etcd:
    image: quay.io/coreos/etcd:latest
    container_name: etcd
    ports:
      - 2379:2379
      - 2380:2380
    command: >
      /usr/local/bin/etcd
      --name node1
      --initial-advertise-peer-urls http://0.0.0.0:2380
      --listen-peer-urls http://0.0.0.0:2380
      --advertise-client-urls http://0.0.0.0:2379
      --listen-client-urls http://0.0.0.0:2379
      --initial-cluster node1=http://0.0.0.0:2380

